# Generated by Django 3.1.1 on 2020-10-06 12:28

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriAnasayfaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagetitle', models.CharField(blank=True, max_length=500, null=True, verbose_name='sayfa ana başlığı ekleyin')),
                ('pagesubtitle', models.CharField(blank=True, max_length=500, null=True, verbose_name='sayfa alt başlığı ekleyin')),
                ('main_image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Ana Sayfa Fotoğrafı')),
            ],
            options={
                'verbose_name': 'Galeri ana sayfası dezenlemesi',
                'verbose_name_plural': 'Galeri ana sayfası düzenlemeleri',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GaleriModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Ana Sayfa fotoğrafı')),
                ('title', models.CharField(max_length=500, verbose_name='Başlık ekleyin')),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True, verbose_name='Alt başlık ekleyin')),
                ('paragrafbir', models.CharField(blank=True, max_length=500, verbose_name='Kısa açıklama ekleyin')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Detay Açıklaması ekleyin')),
                ('imageone', models.ImageField(blank=True, upload_to='', verbose_name='Ana Resim bir')),
                ('imagetwo', models.ImageField(blank=True, upload_to='', verbose_name='Ana Resim iki')),
                ('imagetree', models.ImageField(blank=True, upload_to='', verbose_name='Ana Resim üç')),
                ('imagefour', models.ImageField(blank=True, upload_to='', verbose_name='Ana Resim dört')),
            ],
            options={
                'verbose_name': 'Ürün Açıklaması',
                'verbose_name_plural': 'Ürün Açıklamaları',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='GaleriImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('galerimodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projeler.galerimodel')),
            ],
            options={
                'verbose_name': 'Detay Sayfası Resimi',
                'verbose_name_plural': 'Detay Sayfası Resimleri',
            },
        ),
    ]
