# Generated by Django 3.1.1 on 2020-10-06 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galerianasayfamodel',
            options={'ordering': ['id'], 'verbose_name': 'Projeler ana sayfası dezenlemesi', 'verbose_name_plural': 'Projeler ana sayfası düzenlemeleri'},
        ),
        migrations.AlterModelOptions(
            name='galeriimage',
            options={'verbose_name': 'Projeler Detay Sayfası Resimi', 'verbose_name_plural': 'Projeler Detay Sayfası Resimleri'},
        ),
        migrations.AlterModelOptions(
            name='galerimodel',
            options={'ordering': ['title'], 'verbose_name': 'Projeler Ürün Açıklaması', 'verbose_name_plural': 'Projeler Ürün Açıklamaları'},
        ),
    ]
