# Generated by Django 3.1.1 on 2020-10-11 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeler', '0002_auto_20201006_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galerianasayfamodel',
            options={'ordering': ['id'], 'verbose_name': 'Galeri ana sayfası dezenlemesi', 'verbose_name_plural': 'Galeri ana sayfası düzenlemeleri'},
        ),
        migrations.AlterModelOptions(
            name='galeriimage',
            options={'verbose_name': 'Detay Sayfası Resimi', 'verbose_name_plural': 'Detay Sayfası Resimleri'},
        ),
        migrations.AlterModelOptions(
            name='galerimodel',
            options={'ordering': ['title'], 'verbose_name': 'Galeri Ürün Açıklaması', 'verbose_name_plural': 'Galeri Ürün Açıklamaları'},
        ),
    ]
