# Generated by Django 3.1.1 on 2021-05-04 14:44

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeler', '0004_auto_20201012_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galerianasayfamodel',
            options={'ordering': ['id'], 'verbose_name': 'Projeler ana sayfa', 'verbose_name_plural': 'Projeler ana sayfa'},
        ),
        migrations.AlterModelOptions(
            name='galeriimage',
            options={'verbose_name': 'Projeler Resim', 'verbose_name_plural': 'Projeler Resimleri'},
        ),
        migrations.AlterModelOptions(
            name='galerimodel',
            options={'ordering': ['title'], 'verbose_name': 'Proje', 'verbose_name_plural': 'Projeler'},
        ),
        migrations.RemoveField(
            model_name='galerimodel',
            name='paragrafbir',
        ),
        migrations.AlterField(
            model_name='galerianasayfamodel',
            name='main_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Ana Fotoğraf'),
        ),
        migrations.AlterField(
            model_name='galerianasayfamodel',
            name='pagesubtitle',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='alt başlık'),
        ),
        migrations.AlterField(
            model_name='galerianasayfamodel',
            name='pagetitle',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ana başlık'),
        ),
        migrations.AlterField(
            model_name='galerimodel',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='ek metin  '),
        ),
        migrations.AlterField(
            model_name='galerimodel',
            name='imagefour',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Ana Resim dört'),
        ),
        migrations.AlterField(
            model_name='galerimodel',
            name='imageone',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Ana Resim bir'),
        ),
        migrations.AlterField(
            model_name='galerimodel',
            name='imagetree',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Ana Resim üç'),
        ),
        migrations.AlterField(
            model_name='galerimodel',
            name='imagetwo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Ana Resim iki'),
        ),
        migrations.AlterField(
            model_name='galerimodel',
            name='main_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name="Ana fotoğraf '1920x900'"),
        ),
        migrations.AlterField(
            model_name='galerimodel',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Alt başlık'),
        ),
        migrations.AlterField(
            model_name='galerimodel',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Başlık '),
        ),
    ]
