# Generated by Django 3.1.1 on 2020-09-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogonlyimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogimage',
            options={'verbose_name': 'Resim+içerik ', 'verbose_name_plural': 'Resim+içerik'},
        ),
        migrations.AlterModelOptions(
            name='blogonlyimage',
            options={'verbose_name': 'Blog resim galerisi', 'verbose_name_plural': 'Blog resim galerisi'},
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='author',
            field=models.CharField(blank=True, max_length=500, verbose_name='Yazar'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='main_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Makaleye Ana Fotoğraf Ekleyin'),
        ),
    ]
