# Generated by Django 3.1.1 on 2020-09-23 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200923_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='date',
        ),
    ]
