# Generated by Django 3.1.1 on 2020-09-23 20:42

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200923_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='paragrafbir',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='main_context',
            field=models.CharField(max_length=500, null=True, verbose_name='Giriş parağrafı'),
        ),
        migrations.CreateModel(
            name='BlogonlyContxt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=500, verbose_name='Parağraf ekleyin')),
                ('inspectmodel', models.ForeignKey(on_delete=blog.models.BlogModel, related_name='Context', to='blog.blogmodel')),
            ],
            options={
                'verbose_name': 'Blog Prağraf',
                'verbose_name_plural': 'Blog Parağraflar',
            },
        ),
    ]
