# Generated by Django 3.1.1 on 2020-09-23 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200923_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='paragrafdört',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='paragrafiki',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='paragrafüç',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='titleiki',
        ),
    ]
