# Generated by Django 3.1.1 on 2020-09-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200923_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='main_context',
            field=models.CharField(max_length=500, null=True, verbose_name='Giriş parağrafı Ekleyin'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='main_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Ana Fotoğraf Ekleyin'),
        ),
    ]
