# Generated by Django 3.1.1 on 2020-09-24 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200923_2344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogmodel',
            options={'ordering': ['title'], 'verbose_name': 'Blog yazısı', 'verbose_name_plural': 'Blog yazıları'},
        ),
    ]
