# Generated by Django 3.1.1 on 2020-09-24 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200924_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogimage',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Resim Başlık '),
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='context',
            field=models.CharField(max_length=500, verbose_name='Resim Açıklama'),
        ),
    ]
