# Generated by Django 3.1.1 on 2020-09-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200924_0408'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlognasayfaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagetitle', models.CharField(blank=True, max_length=500, null=True, verbose_name='sayfa ana başlığı ekleyin')),
                ('pagesubtitle', models.CharField(blank=True, max_length=500, null=True, verbose_name='sayfa alt başlığı ekleyin')),
                ('main_image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Ana Sayfa Fotoğrafı')),
            ],
            options={
                'verbose_name': 'Blog ana sayfası dezenlemesi',
                'verbose_name_plural': 'Blog ana sayfası düzenlemeleri',
                'ordering': ['id'],
            },
        ),
    ]
