# Generated by Django 3.1.1 on 2020-09-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blognasayfamodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogonlycontxt',
            options={'verbose_name': 'Blog Paragraf ', 'verbose_name_plural': 'Blog Paragraflar'},
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='main_context',
            field=models.CharField(max_length=500, null=True, verbose_name='Giriş Paragrafı  Ekleyin'),
        ),
        migrations.AlterField(
            model_name='blogonlycontxt',
            name='context',
            field=models.CharField(max_length=500, verbose_name='Paragraf ekleyin'),
        ),
    ]
