# Generated by Django 3.1.1 on 2020-09-27 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200927_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='inspectmodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imageswithcontext', to='blog.blogmodel'),
        ),
        migrations.AlterField(
            model_name='blogonlycontxt',
            name='inspectmodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context', to='blog.blogmodel'),
        ),
        migrations.AlterField(
            model_name='blogonlyimage',
            name='inspectmodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.blogmodel'),
        ),
    ]
