# Generated by Django 3.1.1 on 2020-09-29 16:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200927_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='context',
            field=ckeditor.fields.RichTextField(max_length=500, verbose_name='Resim Açıklama'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='main_context',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500, null=True, verbose_name='Giriş Paragrafı  Ekleyin'),
        ),
        migrations.AlterField(
            model_name='blogonlycontxt',
            name='context',
            field=ckeditor.fields.RichTextField(max_length=500, verbose_name='Paragraf ekleyin'),
        ),
    ]
