# Generated by Django 3.1.1 on 2020-09-29 17:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200929_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='context',
            field=ckeditor.fields.RichTextField(verbose_name='Resim Açıklama'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='main_context',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Giriş Paragrafı  Ekleyin'),
        ),
        migrations.AlterField(
            model_name='blogonlycontxt',
            name='context',
            field=ckeditor.fields.RichTextField(verbose_name='Paragraf ekleyin'),
        ),
    ]
