# Generated by Django 3.1.1 on 2020-10-12 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200929_2009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlognasayfaModel',
        ),
    ]
