# Generated by Django 3.1.1 on 2021-05-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20210503_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='main_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name="Fotoğraf '1920x900' "),
        ),
    ]
