# Generated by Django 3.1.1 on 2020-09-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0002_auto_20200921_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i̇nspectmodel',
            name='paragraf',
            field=models.CharField(blank=True, max_length=500, verbose_name='Açıklama dört'),
        ),
    ]
