# Generated by Django 3.1.1 on 2020-09-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0004_auto_20200921_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='i̇nspectmodel',
            name='titleüç',
            field=models.CharField(blank=True, max_length=500, verbose_name='Başlık ir'),
        ),
    ]
