# Generated by Django 3.1.1 on 2020-09-21 12:47

import anasayfa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0006_auto_20200921_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferansModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='Başlık Ekleyin')),
                ('paragrafbir', models.CharField(blank=True, max_length=500, verbose_name='Açıklama Ekleyin')),
                ('paragrafiki', models.CharField(blank=True, max_length=500, verbose_name='Açıklama Ekleyin')),
            ],
            options={
                'verbose_name': 'Referans',
                'verbose_name_plural': 'Referanslar',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ReferansImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('referansmodel', models.ForeignKey(on_delete=anasayfa.models.ReferansModel, related_name='images', to='anasayfa.referansmodel')),
            ],
            options={
                'verbose_name': 'Resim',
                'verbose_name_plural': 'Resimler',
            },
        ),
    ]
