# Generated by Django 3.1.1 on 2020-09-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0008_whatwedomodel_whowearemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatwedomodel',
            name='video',
            field=models.CharField(blank=True, max_length=500, verbose_name='Video Ekleyin'),
        ),
    ]
