# Generated by Django 3.1.1 on 2020-09-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0009_whatwedomodel_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatwedomodel',
            name='video',
            field=models.CharField(blank=True, max_length=500, verbose_name='Video iframe linki Ekleyin'),
        ),
    ]
