# Generated by Django 3.1.1 on 2020-09-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0010_auto_20200921_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i̇nspectmodel',
            name='paragrafdört',
            field=models.CharField(max_length=500, verbose_name='Açıklama dört'),
        ),
    ]
