# Generated by Django 3.1.1 on 2020-09-24 01:33

import anasayfa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0011_auto_20200922_0245'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlyContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=500, verbose_name='Parağraf ekleyin')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık ekleyin')),
                ('inspectmodel', models.ForeignKey(on_delete=anasayfa.models.İnspectModel, related_name='context', to='anasayfa.i̇nspectmodel')),
            ],
            options={
                'verbose_name': 'Ana sayfa Prağraf',
                'verbose_name_plural': 'Ana sayfa Parağraflar',
            },
        ),
    ]
