# Generated by Django 3.1.1 on 2020-09-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0012_onlycontext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlycontext',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Başlık ekleyin'),
        ),
    ]
