# Generated by Django 3.1.1 on 2020-09-24 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0014_auto_20200924_0443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='i̇nspectmodel',
            old_name='Subtitle',
            new_name='subtitle',
        ),
    ]
