# Generated by Django 3.1.1 on 2020-09-26 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0018_auto_20200927_0012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='i̇nspectmodel',
            options={'ordering': ['id'], 'verbose_name': 'Giriş Açıklaması', 'verbose_name_plural': 'Giriş Açıklaması'},
        ),
        migrations.AlterModelOptions(
            name='referansmodel',
            options={'ordering': ['id'], 'verbose_name': 'Referans', 'verbose_name_plural': 'Referanslar'},
        ),
        migrations.AlterModelOptions(
            name='whatwedomodel',
            options={'ordering': ['id'], 'verbose_name': 'Biz ne yapıyoruz', 'verbose_name_plural': 'Biz ne yapıyoruz'},
        ),
        migrations.AlterModelOptions(
            name='whowearemodel',
            options={'ordering': ['id'], 'verbose_name': 'Biz Kimiz', 'verbose_name_plural': 'Biz Kimiz'},
        ),
    ]
