# Generated by Django 3.1.1 on 2020-09-27 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0021_auto_20200927_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i̇nspectimage',
            name='inspectmodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='anasayfa.i̇nspectmodel'),
        ),
        migrations.AlterField(
            model_name='onlycontext',
            name='inspectmodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context', to='anasayfa.i̇nspectmodel'),
        ),
    ]
