# Generated by Django 3.1.1 on 2020-10-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0022_auto_20200927_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='i̇nspectmodel',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='i̇nspectmodel',
            name='contextmain',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Sol taraftaki ana açıklama '),
        ),
        migrations.AddField(
            model_name='i̇nspectmodel',
            name='formcontext',
            field=models.CharField(blank=True, max_length=500, verbose_name='Formun açıklaması'),
        ),
        migrations.AddField(
            model_name='i̇nspectmodel',
            name='formtitle',
            field=models.CharField(blank=True, max_length=500, verbose_name='Formun başlığı '),
        ),
        migrations.AlterField(
            model_name='i̇nspectmodel',
            name='main_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Arka plan fotoğrafı ekleyin'),
        ),
        migrations.AlterField(
            model_name='i̇nspectmodel',
            name='title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Sol taraftaki ana başlık'),
        ),
    ]
