# Generated by Django 3.1.1 on 2020-10-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0023_auto_20201005_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='İconsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='Ana Başlık Ekleyin')),
                ('paragrafbir', models.CharField(blank=True, max_length=500, verbose_name='Ana Açıklama Ekleyin')),
                ('iconone_title', models.CharField(blank=True, max_length=500, verbose_name='İcon Başlığı Ekleyin')),
                ('iconone_context', models.CharField(blank=True, max_length=500, verbose_name='İcon Açıklaması Ekleyin')),
                ('icontwo_title', models.CharField(blank=True, max_length=500, verbose_name='İcon Başlığı Ekleyin')),
                ('icontwo_context', models.CharField(blank=True, max_length=500, verbose_name='İcon Açıklaması Ekleyin')),
                ('icontree_title', models.CharField(blank=True, max_length=500, verbose_name='İcon Başlığı Ekleyin')),
                ('icontree_context', models.CharField(blank=True, max_length=500, verbose_name='İcon Açıklaması Ekleyin')),
                ('iconfour_title', models.CharField(blank=True, max_length=500, verbose_name='İcon Başlığı Ekleyin')),
                ('iconfour_context', models.CharField(blank=True, max_length=500, verbose_name='İcon Açıklaması Ekleyin')),
            ],
            options={
                'verbose_name': 'İconlarla özet anlatım',
                'verbose_name_plural': 'İconlarlarla özet anlatımlar',
                'ordering': ['id'],
            },
        ),
    ]
