# Generated by Django 3.1.1 on 2020-10-11 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0026_auto_20201012_0055'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MediaFile',
        ),
    ]
