# Generated by Django 3.1.1 on 2020-10-11 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0027_delete_mediafile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='i̇nspectmodel',
            options={'ordering': ['id'], 'verbose_name': '1- Bölüm bir ( form )', 'verbose_name_plural': '1- Bölüm bir ( form )'},
        ),
        migrations.AlterModelOptions(
            name='kuaslogomodel',
            options={'ordering': ['logo'], 'verbose_name': 'Şirket Logosu', 'verbose_name_plural': 'Şirket Logoları'},
        ),
        migrations.AlterModelOptions(
            name='onlycontext',
            options={'verbose_name': 'Ana sayfa paragraf ', 'verbose_name_plural': 'Ana sayfa paragrafları'},
        ),
        migrations.AlterModelOptions(
            name='referansmodel',
            options={'ordering': ['id'], 'verbose_name': '2- Bölüm iki', 'verbose_name_plural': '2- Bölüm iki'},
        ),
        migrations.AlterModelOptions(
            name='whatwedomodel',
            options={'ordering': ['id'], 'verbose_name': '4- Bölüm dört', 'verbose_name_plural': '4- Bölüm dört'},
        ),
        migrations.AlterModelOptions(
            name='whowearemodel',
            options={'ordering': ['id'], 'verbose_name': '3- Bölüm üç', 'verbose_name_plural': '3- Bölüm üç '},
        ),
        migrations.AddField(
            model_name='kuaslogomodel',
            name='minlogo',
            field=models.FileField(null=True, upload_to='', verbose_name='Şirket Küçük Logo Ekleyin '),
        ),
    ]
