# Generated by Django 3.1.1 on 2020-10-12 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0030_auto_20201012_0307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediafile',
            old_name='file',
            new_name='main_image',
        ),
    ]
