# Generated by Django 3.1.1 on 2020-10-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0031_auto_20201012_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='kuaslogomodel',
            name='main_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Arka plan fotoğrafı ekleyin'),
        ),
    ]
