# Generated by Django 3.1.1 on 2020-10-12 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0032_kuaslogomodel_main_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kuaslogomodel',
            options={},
        ),
    ]
