# Generated by Django 3.1.1 on 2020-10-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0033_auto_20201012_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='logo',
            field=models.FileField(null=True, upload_to='', verbose_name='Şirket Logosu Ekleyin '),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='minlogo',
            field=models.FileField(null=True, upload_to='', verbose_name='Şirket Küçük Logo Ekleyin '),
        ),
    ]
