# Generated by Django 3.1.1 on 2020-10-12 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0034_auto_20201012_0317'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MediaFile',
            new_name='KuasLogoModeliki',
        ),
    ]
