# Generated by Django 3.1.1 on 2020-10-12 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0036_auto_20201012_0326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KuasLogoModeliki',
        ),
        migrations.AlterModelOptions(
            name='kuaslogomodel',
            options={'ordering': ['logo'], 'verbose_name': 'Şirket Logosu', 'verbose_name_plural': 'Şirket Logoları'},
        ),
        migrations.RemoveField(
            model_name='kuaslogomodel',
            name='main_image',
        ),
    ]
