# Generated by Django 3.1.1 on 2020-10-12 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0037_auto_20201012_0345'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(upload_to='', verbose_name='Şirket Logosu Ekleyin ')),
                ('minlogo', models.FileField(null=True, upload_to='', verbose_name='Şirket Küçük Logo Ekleyin ')),
            ],
        ),
    ]
