# Generated by Django 3.1.1 on 2020-10-12 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0038_mediafile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kuaslogomodel',
            options={},
        ),
    ]
