# Generated by Django 3.1.1 on 2020-10-12 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0040_mediafileiki'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MediaFileiki',
            new_name='KuasLogoModeliki',
        ),
    ]
