# Generated by Django 3.1.1 on 2020-10-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0042_auto_20201012_0446'),
    ]

    operations = [
        migrations.CreateModel(
            name='İnspectModeliki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='Sol taraftaki ana başlık')),
                ('contextmain', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sol taraftaki ana açıklama ')),
                ('formtitle', models.CharField(blank=True, max_length=500, verbose_name='Formun başlığı ')),
                ('formcontext', models.CharField(blank=True, max_length=500, verbose_name='Formun açıklaması')),
                ('main_image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Arka plan fotoğrafı ekleyin')),
            ],
            options={
                'verbose_name': '1- Bölüm bir ( form )',
                'verbose_name_plural': '1- Bölüm bir ( form )',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='kuaslogomodeliki',
            options={'ordering': ['logo'], 'verbose_name': 'Şirket Logosu .alışıuyor', 'verbose_name_plural': 'Şirket Logoları çalışıyor'},
        ),
    ]
