# Generated by Django 3.1.1 on 2020-10-12 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0043_auto_20201012_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='i̇nspectmodeliki',
            options={'ordering': ['id'], 'verbose_name': '1- Bölüm bir ( yeni )', 'verbose_name_plural': '1- Bölüm bir ( yeni )'},
        ),
    ]
