# Generated by Django 3.1.1 on 2020-10-12 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0044_auto_20201012_1425'),
    ]

    operations = [
        migrations.DeleteModel(
            name='İnspectModeliki',
        ),
        migrations.DeleteModel(
            name='KuasLogoModeliki',
        ),
    ]
