# Generated by Django 3.1.1 on 2021-05-01 23:38

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0046_auto_20210502_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='i̇nspectmodel',
            name='rixhtext',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='ek metin '),
        ),
        migrations.AlterField(
            model_name='i̇nspectmodel',
            name='formcontext',
            field=models.TextField(blank=True, max_length=500, verbose_name="form açıklama '4' "),
        ),
    ]
