# Generated by Django 3.1.1 on 2021-05-01 23:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0047_auto_20210502_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i̇nspectmodel',
            name='rixhtext',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='ek metin '),
        ),
    ]
