# Generated by Django 3.1.1 on 2021-05-01 23:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0048_auto_20210502_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i̇nspectmodel',
            name='rixhtext',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='ek metin '),
        ),
    ]
