# Generated by Django 3.1.1 on 2021-05-02 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0049_auto_20210502_0253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='İconsModel',
        ),
        migrations.DeleteModel(
            name='OnlyContext',
        ),
    ]
