# Generated by Django 3.1.1 on 2021-05-02 02:03

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0050_auto_20210502_0446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='i̇nspectimage',
            options={'verbose_name': 'Resim', 'verbose_name_plural': "Resimler '6' "},
        ),
        migrations.AlterModelOptions(
            name='i̇nspectmodel',
            options={'ordering': ['id'], 'verbose_name': '1- Bölüm bir ', 'verbose_name_plural': '1- Bölüm bir'},
        ),
        migrations.RemoveField(
            model_name='i̇nspectmodel',
            name='rixhtext',
        ),
        migrations.RemoveField(
            model_name='referansmodel',
            name='paragrafbir',
        ),
        migrations.RemoveField(
            model_name='referansmodel',
            name='paragrafiki',
        ),
        migrations.AddField(
            model_name='i̇nspectmodel',
            name='richtext',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name="ek metin '5' "),
        ),
        migrations.AddField(
            model_name='referansmodel',
            name='richtext',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name="ek metin '8' "),
        ),
        migrations.AlterField(
            model_name='referansmodel',
            name='title',
            field=models.CharField(blank=True, max_length=500, verbose_name="Başlık '7'"),
        ),
    ]
