# Generated by Django 3.1.1 on 2021-05-03 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0051_auto_20210502_0503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referansimage',
            options={'verbose_name': 'Resim', 'verbose_name_plural': "Resimler '9'"},
        ),
    ]
