# Generated by Django 3.1.1 on 2021-05-03 13:50

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0052_auto_20210503_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whowearemodel',
            name='paragrafbir',
        ),
        migrations.RemoveField(
            model_name='whowearemodel',
            name='paragrafiki',
        ),
        migrations.RemoveField(
            model_name='whowearemodel',
            name='paragrafüç',
        ),
        migrations.AddField(
            model_name='whowearemodel',
            name='richtext',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name="ek metin '5' "),
        ),
        migrations.AlterField(
            model_name='whowearemodel',
            name='main_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf '),
        ),
        migrations.AlterField(
            model_name='whowearemodel',
            name='sub_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotoğrafı'),
        ),
        migrations.AlterField(
            model_name='whowearemodel',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500, verbose_name='Alt başlık '),
        ),
        migrations.AlterField(
            model_name='whowearemodel',
            name='title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Başlık '),
        ),
    ]
