# Generated by Django 3.1.1 on 2021-05-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0054_auto_20210503_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatwedomodel',
            name='video',
            field=models.CharField(blank=True, max_length=500, verbose_name="Video iframe linki '19' "),
        ),
    ]
