# Generated by Django 3.1.1 on 2021-05-03 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0055_auto_20210503_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kuaslogomodel',
            options={'ordering': ['logo'], 'verbose_name': 'Kuas logo', 'verbose_name_plural': 'Kuas logo'},
        ),
    ]
