# Generated by Django 3.1.1 on 2020-09-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iletisim', '0004_auto_20200918_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='i̇nfo',
            options={'ordering': ['email'], 'verbose_name': 'Şirket İletişim Bilgisi', 'verbose_name_plural': 'Şirket İletişim Bilgileri'},
        ),
        migrations.AddField(
            model_name='i̇nfo',
            name='main_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Ana Fotoğraf Ekleyin'),
        ),
        migrations.AddField(
            model_name='i̇nfo',
            name='title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ana Başlık '),
        ),
    ]
