# Generated by Django 3.1.1 on 2020-10-05 15:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iletisim', '0007_auto_20201005_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i̇nfo',
            name='main_context',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Ana Açıklama Ekleyin'),
        ),
    ]
