# Generated by Django 3.1.1 on 2020-10-05 15:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iletisim', '0008_auto_20201005_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i̇nfo',
            name='campanydescrp',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Şirket Açıklaması '),
        ),
    ]
