# Generated by Django 3.1.1 on 2020-10-15 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iletisim', '0009_auto_20201005_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='i̇nfo',
            name='campanyname',
        ),
    ]
