# Generated by Django 3.1.1 on 2021-05-05 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iletisim', '0010_remove_i̇nfo_campanyname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name'], 'verbose_name': 'Mesaj', 'verbose_name_plural': 'Mesajlar'},
        ),
        migrations.AlterModelOptions(
            name='i̇nfo',
            options={'ordering': ['email'], 'verbose_name': 'Kuas  Bilgi', 'verbose_name_plural': 'Kuas  Bilgi'},
        ),
    ]
