# Generated by Django 3.1.1 on 2020-09-21 18:42

from django.db import migrations, models
import galeri.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='Başlık bir')),
                ('paragrafbir', models.CharField(blank=True, max_length=500, verbose_name='Açıklama bir')),
                ('paragrafiki', models.CharField(blank=True, max_length=500, verbose_name='Açıklama iki')),
            ],
            options={
                'verbose_name': 'Ürün Açıklaması',
                'verbose_name_plural': 'Ürün Açıklaması',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='GaleriImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('galerimodel', models.ForeignKey(on_delete=galeri.models.GaleriModel, related_name='images', to='galeri.galerimodel')),
            ],
            options={
                'verbose_name': 'Resim',
                'verbose_name_plural': 'Resimler',
            },
        ),
    ]
