# Generated by Django 3.1.1 on 2020-09-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galerimodel',
            name='title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Başlık '),
        ),
    ]
