# Generated by Django 3.1.1 on 2020-09-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeri', '0002_auto_20200921_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='galerimodel',
            name='imagefour',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Açıklama dört'),
        ),
        migrations.AddField(
            model_name='galerimodel',
            name='imageone',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Resim bir'),
        ),
        migrations.AddField(
            model_name='galerimodel',
            name='imagetree',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Açıklama üç'),
        ),
        migrations.AddField(
            model_name='galerimodel',
            name='imagetwo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Açıklama iki'),
        ),
        migrations.DeleteModel(
            name='GaleriImage',
        ),
    ]
