# Generated by Django 3.1.1 on 2020-09-22 00:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeri', '0005_galerimodel_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galerimodel',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500, null=True, verbose_name='açıklama üç'),
        ),
    ]
