# Generated by Django 3.1.1 on 2020-09-22 00:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeri', '0007_auto_20200922_0308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galerimodel',
            name='paragrafiki',
        ),
        migrations.AlterField(
            model_name='galerimodel',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Detay Açıklaması ekleyin'),
        ),
        migrations.AlterField(
            model_name='galerimodel',
            name='paragrafbir',
            field=models.CharField(blank=True, max_length=500, verbose_name='Kısa Açıklama ekleyin'),
        ),
    ]
