# Generated by Django 3.1.1 on 2020-09-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeri', '0009_galerianasayfamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galerianasayfamodel',
            name='pagesubtitle',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='sayfa alt başlığı ekleyin'),
        ),
        migrations.AlterField(
            model_name='galerianasayfamodel',
            name='pagetitle',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='sayfa ana başlığı ekleyin'),
        ),
    ]
