# Generated by Django 3.1.1 on 2020-09-27 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galeri', '0011_auto_20200926_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeriimage',
            name='galerimodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='galeri.galerimodel'),
        ),
    ]
