# Generated by Django 3.1.1 on 2020-10-06 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeri', '0012_auto_20200927_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galerimodel',
            options={'ordering': ['title'], 'verbose_name': 'Galeri Ürün Açıklaması', 'verbose_name_plural': 'Galeri Ürün Açıklamaları'},
        ),
    ]
