# Generated by Django 3.1.1 on 2021-05-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeri', '0013_auto_20201006_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galerianasayfamodel',
            options={'ordering': ['id'], 'verbose_name': 'Galeri ana sayfa', 'verbose_name_plural': 'Galeri ana sayfa'},
        ),
        migrations.AlterField(
            model_name='galerianasayfamodel',
            name='main_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name="fotoğraf '1920x900'"),
        ),
        migrations.AlterField(
            model_name='galerianasayfamodel',
            name='pagesubtitle',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='altbaşlık '),
        ),
        migrations.AlterField(
            model_name='galerianasayfamodel',
            name='pagetitle',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Anasayfa başlık '),
        ),
    ]
