# Generated by Django 3.1.1 on 2021-05-04 14:30

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeri', '0014_auto_20210504_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galerimodel',
            options={'ordering': ['title'], 'verbose_name': 'Galeri Ürün', 'verbose_name_plural': 'Galeri Ürünler'},
        ),
        migrations.RemoveField(
            model_name='galerimodel',
            name='paragrafbir',
        ),
        migrations.AlterField(
            model_name='galerimodel',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='ek metin  '),
        ),
        migrations.AlterField(
            model_name='galerimodel',
            name='imagefour',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Ana Resim dört'),
        ),
        migrations.AlterField(
            model_name='galerimodel',
            name='imageone',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Ana Resim bir'),
        ),
        migrations.AlterField(
            model_name='galerimodel',
            name='imagetree',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Ana Resim üç'),
        ),
        migrations.AlterField(
            model_name='galerimodel',
            name='imagetwo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Ana Resim iki'),
        ),
    ]
