# Generated by Django 3.1.1 on 2021-05-04 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeri', '0015_auto_20210504_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeriimage',
            options={'verbose_name': 'Detay Resim', 'verbose_name_plural': 'Detay Resim'},
        ),
    ]
