# Generated by Django 3.1.1 on 2020-09-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoruModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soru', models.CharField(max_length=500, verbose_name='Soru Ekleyin')),
                ('paragrafbir', models.CharField(max_length=500, verbose_name='Cevap Ekleyin')),
            ],
            options={
                'verbose_name': 'Soru',
                'verbose_name_plural': 'Sorular',
                'ordering': ['id'],
            },
        ),
    ]
