# Generated by Django 3.1.1 on 2020-09-23 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorular', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sorumodel',
            old_name='paragrafbir',
            new_name='cevap',
        ),
    ]
