# Generated by Django 3.1.1 on 2020-09-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorular', '0003_sorumodel_pagetitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaşlıkSoruModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagetitle', models.CharField(max_length=500, null=True, verbose_name='sayfa ana başlığı ekleyin')),
                ('pagesubtitle', models.CharField(max_length=500, null=True, verbose_name='sayfa ana başlığı ekleyin')),
            ],
            options={
                'verbose_name': 'Soru sayfası ana başlığı',
                'verbose_name_plural': 'Soru sayfası ana başlığı',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='sorumodel',
            name='pagetitle',
        ),
    ]
