# Generated by Django 3.1.1 on 2020-09-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorular', '0004_auto_20200923_1815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='başlıksorumodel',
            options={'ordering': ['id'], 'verbose_name': 'Sorular sayfası ana başlığı', 'verbose_name_plural': 'Sorular sayfası ana başlığı'},
        ),
        migrations.AddField(
            model_name='başlıksorumodel',
            name='maincontent',
            field=models.CharField(max_length=500, null=True, verbose_name='sayfa ana açıklamasını ekleyin'),
        ),
        migrations.AlterField(
            model_name='başlıksorumodel',
            name='pagesubtitle',
            field=models.CharField(max_length=500, null=True, verbose_name='sayfa alt başlığı ekleyin'),
        ),
    ]
