# Generated by Django 3.1.1 on 2020-09-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorular', '0005_auto_20200923_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='başlıksorumodel',
            options={'ordering': ['id'], 'verbose_name': 'Sorular ana sayfası dezenlemesi', 'verbose_name_plural': 'Sorular ana sayfası düzenlemeleri'},
        ),
        migrations.AddField(
            model_name='başlıksorumodel',
            name='main_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Ana Sayfa Fotoğrafı'),
        ),
    ]
