# Generated by Django 3.1.1 on 2020-09-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorular', '0006_auto_20200924_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='başlıksorumodel',
            name='maincontent',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='sayfa ana açıklamasını ekleyin'),
        ),
        migrations.AlterField(
            model_name='başlıksorumodel',
            name='pagesubtitle',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='sayfa alt başlığı ekleyin'),
        ),
    ]
