# Generated by Django 3.1.1 on 2020-10-11 23:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorular', '0007_auto_20200926_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='başlıksorumodel',
            name='maincontent',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500, null=True, verbose_name='sayfa ana açıklamasını ekleyin'),
        ),
        migrations.AlterField(
            model_name='sorumodel',
            name='cevap',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Cevap Ekleyin'),
        ),
    ]
