# Generated by Django 3.1.1 on 2021-05-04 16:32

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorular', '0008_auto_20201012_0204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='başlıksorumodel',
            options={'ordering': ['id'], 'verbose_name': 'Sorular ana sayfa ', 'verbose_name_plural': 'Sorular ana sayfa'},
        ),
        migrations.AlterField(
            model_name='başlıksorumodel',
            name='main_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Ana Fotoğraf'),
        ),
        migrations.AlterField(
            model_name='başlıksorumodel',
            name='maincontent',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=500, null=True, verbose_name='sayfa  açıklamasını '),
        ),
        migrations.AlterField(
            model_name='başlıksorumodel',
            name='pagesubtitle',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='alt başlık '),
        ),
        migrations.AlterField(
            model_name='başlıksorumodel',
            name='pagetitle',
            field=models.CharField(max_length=500, null=True, verbose_name='ana başlık '),
        ),
        migrations.AlterField(
            model_name='sorumodel',
            name='cevap',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Cevap '),
        ),
        migrations.AlterField(
            model_name='sorumodel',
            name='soru',
            field=models.CharField(max_length=500, verbose_name='Soru '),
        ),
    ]
